# Generated by Django 3.2 on 2021-05-05 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_react_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lead',
            options={'ordering': ['-created_at', 'shift', 'message_body', 'Fault_description']},
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='Corealarm',
            new_name='Core_alarm',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='Datacomalarm',
            new_name='Datacom_alarm',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='Poweralarm',
            new_name='Power_alarm',
        ),
        migrations.RenameField(
            model_name='lead',
            old_name='Transmissionalarm',
            new_name='Transmission_alarm',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='dept',
        ),
    ]
