# Generated by Django 3.2 on 2021-05-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_react_app', '0002_auto_20210505_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corealarm',
            name='alarm_name',
            field=models.CharField(default='No Alarm', max_length=500),
        ),
        migrations.AlterField(
            model_name='datacomalarm',
            name='alarm_name',
            field=models.CharField(default='No Alarm', max_length=500),
        ),
        migrations.AlterField(
            model_name='poweralarm',
            name='alarm_name',
            field=models.CharField(default='No Alarm', max_length=500),
        ),
        migrations.AlterField(
            model_name='transmissionalarm',
            name='alarm_name',
            field=models.CharField(default='No Alarm', max_length=500),
        ),
    ]
