# Generated by Django 3.2 on 2021-05-05 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_react_app', '0003_auto_20210505_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='Core_alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corealarm', to='drf_react_app.corealarm'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Datacom_alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='datacomalarm', to='drf_react_app.datacomalarm'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Power_alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='poweralarm', to='drf_react_app.poweralarm'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Transmission_alarm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transmissionalarm', to='drf_react_app.transmissionalarm'),
        ),
    ]
