# Generated by Django 3.2 on 2021-05-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_react_app', '0004_auto_20210505_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corealarm',
            name='alarm_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='corealarm',
            name='alarm_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='datacomalarm',
            name='alarm_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='datacomalarm',
            name='alarm_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='poweralarm',
            name='alarm_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='poweralarm',
            name='alarm_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='transmissionalarm',
            name='alarm_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='transmissionalarm',
            name='alarm_type',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
