# Generated by Django 3.2 on 2021-05-05 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_react_app', '0005_auto_20210505_1027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corealarm',
            name='alarm_type',
        ),
        migrations.RemoveField(
            model_name='datacomalarm',
            name='alarm_type',
        ),
        migrations.RemoveField(
            model_name='poweralarm',
            name='alarm_type',
        ),
        migrations.RemoveField(
            model_name='transmissionalarm',
            name='alarm_type',
        ),
        migrations.AlterField(
            model_name='corealarm',
            name='alarm_description',
            field=models.TextField(blank=True, default='No description'),
        ),
        migrations.AlterField(
            model_name='corealarm',
            name='alarm_name',
            field=models.CharField(default='No Alarm', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datacomalarm',
            name='alarm_description',
            field=models.TextField(blank=True, default='No description'),
        ),
        migrations.AlterField(
            model_name='datacomalarm',
            name='alarm_name',
            field=models.CharField(default='No Alarm', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='poweralarm',
            name='alarm_description',
            field=models.TextField(blank=True, default='No description'),
        ),
        migrations.AlterField(
            model_name='poweralarm',
            name='alarm_name',
            field=models.CharField(default='No Alarm', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='transmissionalarm',
            name='alarm_description',
            field=models.TextField(blank=True, default='No description'),
        ),
        migrations.AlterField(
            model_name='transmissionalarm',
            name='alarm_name',
            field=models.CharField(default='No Alarm', max_length=500, null=True),
        ),
    ]
