# Generated by Django 3.2 on 2021-05-05 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drf_react_app', '0007_auto_20210505_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='Fault_description',
            field=models.TextField(blank=True, default='No issue', max_length=250, null=True, verbose_name='Fault description'),
        ),
    ]
